# Generated by Django 4.0.5 on 2022-06-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('title_ky', models.CharField(max_length=150, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=250, null=True, verbose_name='заголовок')),
                ('short_content', models.CharField(max_length=400, verbose_name='краткое описание')),
                ('short_content_ru', models.CharField(max_length=400, null=True, verbose_name='краткое описание')),
                ('short_content_ky', models.CharField(max_length=400, null=True, verbose_name='краткое описание')),
                ('url', models.URLField(verbose_name='ссылка на видео')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('categories', models.ManyToManyField(to='core.categories', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'видео ролик',
                'verbose_name_plural': 'видео ролики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('image', models.ImageField(upload_to='news_image/', verbose_name='изображение')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='заголовок')),
                ('title_ky', models.CharField(max_length=250, null=True, verbose_name='заголовок')),
                ('short_content', models.CharField(max_length=400, verbose_name='краткое описание')),
                ('short_content_ru', models.CharField(max_length=400, null=True, verbose_name='краткое описание')),
                ('short_content_ky', models.CharField(max_length=400, null=True, verbose_name='краткое описание')),
                ('content', models.TextField(verbose_name='контент')),
                ('content_ru', models.TextField(null=True, verbose_name='контент')),
                ('content_ky', models.TextField(null=True, verbose_name='контент')),
                ('views', models.IntegerField(default=0, null=True, verbose_name='просмотры')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('categories', models.ManyToManyField(to='core.categories', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
