# Generated by Django 4.0.5 on 2022-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AddField(
            model_name='videos',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
    ]
