# Generated by Django 4.0.5 on 2022-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articles_is_published_videos_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='short_content',
            field=models.CharField(max_length=900, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='short_content_ky',
            field=models.CharField(max_length=900, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='short_content_ru',
            field=models.CharField(max_length=900, null=True, verbose_name='краткое описание'),
        ),
    ]
